Repository boostcampwm-2024/and02_weQuiz, pull requests merged in 2024-12, with the labels that each got.

#173 docs: README 수정
  README.md
Labels: 📝docs, 🐧pengcon, 👩‍🌾915dbfl, 🧑‍💻Cheonilyeong, ✈jay200333, 🎩moyeongmin

#180 fix: ai 주제 작성하지 않고 문제 생성 가능한 오류 및 알림이 없을 때 텍스트 그려지지 않던 상황 수정
  feature/main/src/main/java/kr/boostcamp_2024/course/main/presentation/NotificationScreen.kt
  feature/main/src/main/res/values/strings.xml
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/QuizAiDialog.kt
Labels: 🐛fix, 🐧pengcon

#176 refactor: build logic 리팩토링
  app/src/main/java/kr/boostcamp_2024/course/wequiz/ui/WeQuizNavHost.kt
  build-logic/src/main/java/convention.android.application.gradle.kts
  build-logic/src/main/java/convention.android.feature.gradle.kts
  build-logic/src/main/java/kr/boostcamp_2024/course/build_logic/ComposeAndroid.kt
  build-logic/src/main/java/kr/boostcamp_2024/course/build_logic/Firebase.kt
  build-logic/src/main/java/kr/boostcamp_2024/course/build_logic/HiltAndroid.kt
  build-logic/src/main/java/kr/boostcamp_2024/course/build_logic/KotlinAndroid.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/kr/boostcamp_2024/course/main/navigation/MainNavigation.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/presentation/MainScreen.kt
Labels: ♻️refactor, 👩‍🌾915dbfl

#181 refactor: 네트워크 통신 필요로 하는 버튼 multiple click 개선
  feature/category/src/main/java/kr/boostcamp_2024/course/category/presentation/CreateCategoryScreen.kt
  feature/login/src/main/java/kr/boostcamp_2024/course/login/presentation/SignUpScreen.kt
  feature/login/src/main/java/kr/boostcamp_2024/course/login/viewmodel/SignUpViewModel.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/question/CreateQuestionScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/question/GeneralQuestionScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/question/OwnerQuestionScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/question/QuestionScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/quiz/CreateQuizScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/viewmodel/CreateQuestionViewModel.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/CreateStudyScreen.kt
Labels: ♻️refactor, 👩‍🌾915dbfl

#182 refactor: 알림 아이콘 라벨 추가
  feature/main/src/main/java/kr/boostcamp_2024/course/main/presentation/MainScreen.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/viewmodel/MainViewModel.kt
Labels: ♻️refactor, ✈jay200333

#183 fix: 텍스트 필드 길이 제한 개선
  feature/category/src/main/java/kr/boostcamp_2024/course/category/presentation/CreateCategoryScreen.kt
  feature/category/src/main/java/kr/boostcamp_2024/course/category/viewmodel/CreateCategoryViewModel.kt
  feature/category/src/main/res/values-ko/strings.xml
  feature/category/src/main/res/values-zh/strings.xml
  feature/category/src/main/res/values/strings.xml
  feature/login/src/main/java/kr/boostcamp_2024/course/login/presentation/SignUpScreen.kt
  feature/login/src/main/java/kr/boostcamp_2024/course/login/viewmodel/SignUpViewModel.kt
  feature/login/src/main/res/values-ko/strings.xml
  feature/login/src/main/res/values-zh/strings.xml
  feature/login/src/main/res/values/strings.xml
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/CreateQuestionContent.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/quiz/CreateQuizScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/viewmodel/CreateQuestionViewModel.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/viewmodel/CreateQuizViewModel.kt
  feature/quiz/src/main/res/values-ko/strings.xml
  feature/quiz/src/main/res/values-zh/strings.xml
  feature/quiz/src/main/res/values/strings.xml
  feature/study/src/main/java/kr/boostcamp_2024/course/study/CreateStudyViewModel.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/CreateStudyScreen.kt
  feature/study/src/main/res/values-ko/strings.xml
  feature/study/src/main/res/values-zh/strings.xml
  feature/study/src/main/res/values/strings.xml
Labels: 🐛fix, 🧑‍💻Cheonilyeong

#186 fix: 가이드 노션 작성 및 연결, 가이드 스크린 작성
  core/data/src/main/java/kr/boostcamp_2024/course/data/di/RepositoryModule.kt
  core/data/src/main/java/kr/boostcamp_2024/course/data/repository/GuideRepositoryImpl.kt
  core/domain/src/main/java/kr/boostcamp_2024/course/domain/repository/GuideRepository.kt
  feature/category/src/main/res/values-ko/strings.xml
  feature/main/build.gradle.kts
  feature/main/src/main/java/kr/boostcamp_2024/course/main/component/BaseGuideScreen.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/component/GuideDialog.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/presentation/MainScreen.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/viewmodel/MainViewModel.kt
  feature/main/src/main/res/drawable/sample_profile1.png
  feature/main/src/main/res/raw/anim_arrow.json
  feature/main/src/main/res/values-ko/strings.xml
  feature/main/src/main/res/values-zh/strings.xml
  feature/main/src/main/res/values/strings.xml
Labels: 🐛fix, ✨feat, 🎩moyeongmin, 🔧refactor

#187 docs: README 배지 추가,실시간 이미지 변경, 문서 링크 추가
  README.md
Labels: 📝docs, ✈jay200333

#188 refactor: 디자인 시스템 이미지 수정 및 적용
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/theme/component/WeQuizPhotoPicker.kt
  feature/category/src/main/java/kr/boostcamp_2024/course/category/presentation/CreateCategoryScreen.kt
  feature/login/src/main/java/kr/boostcamp_2024/course/login/presentation/SignUpScreen.kt
  feature/login/src/main/java/kr/boostcamp_2024/course/login/viewmodel/SignUpViewModel.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/quiz/CreateQuizScreen.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/CreateStudyScreen.kt
Labels: ♻️refactor, 🐧pengcon, 👩‍🌾915dbfl, 🧑‍💻Cheonilyeong, ✈jay200333, 🎩moyeongmin

#190 refactor: 문제 생성 페이지 ime padding 적용
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/theme/component/WeQuizChatBubble.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/BlankQuestionContentUi.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/question/CreateQuestionScreen.kt
Labels: ♻️refactor, 🐧pengcon, 🎩moyeongmin

#191 fix: 팀별 QA 추가 작업
  app/build.gradle.kts
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/theme/component/WeQuizChatBubble.kt
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/theme/component/WeQuizImageLargeTopAppBar.kt
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/theme/component/WeQuizPhotoPicker.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/component/GuideDialog.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/presentation/MainScreen.kt
  feature/main/src/main/res/values-ko/strings.xml
  feature/main/src/main/res/values-zh/strings.xml
  feature/main/src/main/res/values/strings.xml
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/QuizDataText.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/QuizTopAppBar.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/quiz/QuizScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/viewmodel/CreateQuestionViewModel.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/component/CustomIconButton.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/component/CustomPropertyTab.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/DetailStudyScreen.kt
Labels: 🐛fix, 🧑‍💻Cheonilyeong

#193 fix: 팀별 QA 추가 오류 해결
  app/build.gradle.kts
  core/data/src/main/java/kr/boostcamp_2024/course/data/model/ChoiceQuestionDTO.kt
  core/data/src/main/java/kr/boostcamp_2024/course/data/repository/QuestionRepositoryImpl.kt
  feature/category/src/main/java/kr/boostcamp_2024/course/category/component/CategorySettingMenu.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/component/NotificationItem.kt
  feature/main/src/main/res/values/strings.xml
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/question/PieChartScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/viewmodel/QuestionViewModel.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/viewmodel/UserQuestionViewModel.kt
  feature/quiz/src/main/res/values-ko/strings.xml
  feature/quiz/src/main/res/values-zh/strings.xml
  feature/quiz/src/main/res/values/strings.xml
Labels: 🐛fix, ♻️refactor

#195 docs: 기능 GIF 수정
  README.md
Labels: 📝docs
