Repository boostcampwm-2024/and02_weQuiz, pull requests merged in 2025-01, with the labels that each got.

#197 refactor: preview 수정 및 state Hoisting 적용
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/annotation/PreviewAnnotations.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/presentation/NotificationScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/QuizOwnerDialog.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/QuizSolveTimeSlider.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/QuizTopAppBar.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/RadioTextButton.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/RealTimeQuestion.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/RealTimeQuizGuideContent.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/UserQuestion.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/question/CreateQuestionScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/question/QuestionDetailScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/quiz/GeneralQuizResultScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/quiz/OwnerQuizResultScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/quiz/QuizResultScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/utils/QuestionParameterProvider.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/CreateStudyScreen.kt
Labels: ♻️refactor, 🐧pengcon

#198 refactor: preview 수정 및 state Hoisting 적용
  core/data/src/main/java/kr/boostcamp_2024/course/data/model/NotificationDTO.kt
  core/domain/src/main/java/kr/boostcamp_2024/course/domain/model/Notification.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/component/BaseGuideScreen.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/component/GuideDialog.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/component/MainDropDownMenu.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/component/NotificationItem.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/component/NotificationTopAppBar.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/component/StudyGroupItem.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/presentation/NotificationScreen.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/viewmodel/NotificationViewModel.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/BlankQuestionContent.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/BlankQuestionContentUi.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/BlankQuestionDescription.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/ChoiceQuestionContent.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/question/PieChartScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/quiz/QuizStatisticsDialog.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/CategoryListScreen.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/CreateGroupDialog.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/DetailStudyScreen.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/GroupListScreen.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/viewmodel/DetailStudyViewModel.kt
Labels: ♻️refactor, ✈jay200333

#199 refactor: preview 수정 및 state Hoisting 적용
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/theme/component/WeQuizBaseDialog.kt
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/theme/component/WeQuizChatBubble.kt
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/theme/component/WeQuizLoadingIndicator.kt
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/theme/component/WeQuizPhotoPicker.kt
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/theme/component/WeQuizRoundedImage.kt
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/theme/component/WeQuizTextField.kt
  core/designsystem/src/main/java/kr/boostcamp_2024/course/designsystem/ui/theme/component/WeQuizValidateTextField.kt
  feature/category/src/main/java/kr/boostcamp_2024/course/category/presentation/CreateCategoryScreen.kt
  feature/login/src/main/java/kr/boostcamp_2024/course/login/presentation/SignUpScreen.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/component/GuideDialog.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/presentation/MainScreen.kt
  feature/main/src/main/java/kr/boostcamp_2024/course/main/viewmodel/MainViewModel.kt
  feature/main/src/main/res/values-ko/strings.xml
  feature/main/src/main/res/values-zh/strings.xml
  feature/main/src/main/res/values/strings.xml
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/QuizTopAppBar.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/RadioTextButton.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/question/QuestionDetailScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/quiz/CreateQuizScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/quiz/OwnerQuizResultScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/quiz/QuizScreen.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/component/CategoryItem.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/component/CreateStudyTopAppBar.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/component/CustomPropertyTab.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/component/DescriptionTextField.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/component/LeftChatBubble.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/component/MembersDropDownMenu.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/component/StudyCreationGuide.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/component/StudyGroupMemberItem.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/component/StudySubmitButton.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/component/TitleTextField.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/CategoryListScreen.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/CreateStudyScreen.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/DetailStudyScreen.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/GroupListScreen.kt
  feature/study/src/main/res/values-ko/strings.xml
  feature/study/src/main/res/values-zh/strings.xml
  feature/study/src/main/res/values/strings.xml
Labels: ♻️refactor, 🧑‍💻Cheonilyeong

#200 refactor: preview 수정 및 state Hoisting 적용
  feature/category/src/main/java/kr/boostcamp_2024/course/category/component/CategorySettingMenu.kt
  feature/category/src/main/java/kr/boostcamp_2024/course/category/presentation/CategoryScreen.kt
  feature/category/src/main/java/kr/boostcamp_2024/course/category/presentation/CreateCategoryScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/CreateBlankQuestionContent.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/CreateChoiceItems.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/CreateQuestionContent.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/Question.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/QuestionConent.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/QuestionDescription.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/QuestionDetailTopAppBar.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/QuestionItems.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/component/QuestionSolution.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/presentation/quiz/QuizResultScreen.kt
  feature/quiz/src/main/java/kr/boostcamp_2024/course/quiz/utils/QuizContentPreviewParameterProvider.kt
  feature/study/src/main/java/kr/boostcamp_2024/course/study/presentation/DetailStudyScreen.kt
Labels: ♻️refactor, 🎩moyeongmin
